message(STATUS " !!! Inside my FindXMLRPC.cmake!")

set(IFM3D_CMAKE_MODULE_PATH_OLD ${CMAKE_MODULE_PATH})
unset(CMAKE_MODULE_PATH)
find_package(XMLRPC REQUIRED c++ client)
set(CMAKE_MODULE_PATH ${IFM3D_CMAKE_MODULE_PATH_OLD})

if(XMLRPC_FOUND AND NOT TARGET XMLRPC::XMLRPC)
  add_library(XMLRPC::XMLRPC INTERFACE IMPORTED)
  set_target_properties(XMLRPC::XMLRPC PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${XMLRPC_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${XMLRPC_LIBRARIES}"
  )
endif()